csf3:

  hpc:

    scheduler: slurm
    jobscript_shebang: "#!/bin/bash --login"
    max_array_task_id: 25000
    memory_per_core_gb: 8
    memory_per_core_gb_by_partition:
      multicore: 8
      interactive: 8
      serial: 5
      multicore_small: 5
      himem: 32
    parallel_environments:
      serial: [1, 1]
      multicore: [2, 168]

  software:

    gaussian:
      executable_path: "$g09root/g09/g09"
      modules: ["apps/binapps/gaussian/g09d01_em64t"]

    aimall:
      executable_path: "~/AIMAll/aimqb.ish"

    ferebus:
      executable_path: "$HOME/.local/bin/ferebus"
      pyferebus_platform: "CSF3"

    ariadne_runtime:
      modules:
        - "compilers/intel/oneapi/2025.0.1"
        - "umf compiler-rt tbb compiler"
        - "mkl/2025.0"

    amber:
      modules: ["apps/intel-17.0/amber/18-at19-may2019"]
      executable_path: sander

    cp2k:
      executable_path: cp2k.ssmp
      modules: ["apps/binapps/cp2k/6.1.0"]
      data_path: "/opt/apps/apps/intel-17.0/cp2k/6.1.0/data"

    dlpoly:
      modules: ["compilers/intel/18.0.3"]

    orca:
      executable_path: $ORCA_HOME/orca
      modules: ["apps/binapps/orca/5.0.3"]

    pandora:
      modules: ["mpi/intel-18.0/openmpi/4.0.1"]

    python:
      env_name: "ichor-csf3"
      python_path: "$HOME/.venv/ichor-csf3/bin/python"
      modules: []

    plumed:
      kernel_path: "$HOME/opt/plumed-2.10.0/lib/libplumedKernel.so"
      library_path: "$HOME/opt/plumed-2.10.0/lib"
      modules: []

    tyche:
      modules: ["compilers/intel/18.0.3"]

csf4:

  hpc:

    scheduler: slurm
    jobscript_shebang: "#!/bin/bash"
    max_array_task_id: 25000
    memory_per_core_gb: 4
    memory_per_core_gb_by_partition:
      serial: 4
      multicore: 4
      multinode: 4
    parallel_environments:
      serial: [1, 1]
      multicore: [2, 32]

  software:

    aimall:
      executable_path: "~/AIMAll/aimqb.ish"

    ferebus:
      executable_path: "$HOME/.local/bin/ferebus"
      pyferebus_platform: "CSF4"

    gaussian:
      executable_path: "$g16root/g16/g16"
      modules: ["gaussian/g16c01_em64t_detectcpu"]

    ariadne_runtime:
      modules:
        - "compilers/oneapi/2024.2.0"
        - "compiler-rt tbb compiler"
        - "mkl/2024.2"

    amber:
      modules: ["amber/20.12-iomkl-2020.02-ambertools-21.12"]
      executable_path: sander

    cp2k:
      executable_path: cp2k.popt
      modules: [cp2k/6.1-iomkl-2020.02]
      data_path: "/opt/software/RI/apps/CP2K/6.1-iomkl-2020.02/data"

    dlpoly:
      modules: ["iomkl/2020.02"]

    orca:
      executable_path: orca
      modules: ["orca/5.0.4-gompi-2021a"]

    pandora:
      modules: ["iomkl/2020.02"]

    python:
      env_name: "ichor-csf4"
      python_path: "~/.venv/ichor-csf4/bin/python"
      modules: ["python/3.11.3-gcccore-12.3.0"]

    plumed:
      kernel_path: "$HOME/opt/plumed-2.10.0/lib/libplumedKernel.so"
      library_path: "$HOME/opt/plumed-2.10.0/lib"
      modules: []

    tyche:
      modules: ["iomkl/2020.02"]

ffluxlab:

  hpc:

    parallel_environments:
      smp: [2, 44]

  software:

    aimall:
      executable_path: aimall
      modules: ["apps/aimall/19.02.13"]

    gaussian:
      executable_path: g09
      modules: ["apps/gaussian/g09"]

    amber:
      modules: ["apps/amber/18-at19"]

    cp2k:
      modules: ["apps/cp2k/6.1.0"]
      data_path: "/home/modules/apps/cp2k/6.1.0/data"

    dlpoly:
      modules: ["mpi/intel/18.0.3"]

    pandora:
      modules: ["compilers/intel/18.0.3", "libs/python/pyscf/1.7.4"]

    python:
      modules: ["apps/anaconda3/3.7.6"]

    tyche:
      modules: ["compilers/intel/18.0.3"]
