"""Internal geometry-novelty protocol coefficients.

These values are deliberately not campaign.yaml knobs. The public campaign
config controls how the geometry-novelty scale is estimated; this module owns
how that scale is mapped into Phase B and ARIADNE safety/acquisition terms.
"""
from __future__ import annotations


PHASE_B_MIN_SEPARATION_SCALE = 0.5

GEOMETRY_NOVELTY_SCORE_TRANSFORM = "linear_cap"

MOVEMENT_BAND_ENABLED = True
MOVEMENT_BAND_METRIC = "aligned_active_rmsd"
MOVEMENT_BAND_LOCAL_STATISTIC = "p25"
MOVEMENT_BAND_HARD_MIN_FRACTION = 0.10
MOVEMENT_BAND_TARGET_LOW_FRACTION = 0.25
MOVEMENT_BAND_TARGET_PEAK_FRACTION = 0.40
MOVEMENT_BAND_TARGET_HIGH_FRACTION = 0.75
MOVEMENT_BAND_HARD_MAX_FRACTION = 1.25

MOVEMENT_UTILITY_ENABLED = True
MOVEMENT_UTILITY_DIRECTION = "initial_projected_acquisition_gradient"
MOVEMENT_UTILITY_LAMBDA_MOVE = 0.75
MOVEMENT_UTILITY_BAND_FRACTION = 0.75
MOVEMENT_UTILITY_PROGRESS_FRACTION = 0.25
MOVEMENT_UTILITY_LOW_SOFTNESS_FRACTION = 0.10
MOVEMENT_UTILITY_HIGH_SOFTNESS_FRACTION = 0.40

FULLSPACE_RESIDUAL_SCALE = "local_neighbour_median"
FULLSPACE_FIXED_RESIDUAL_SCALE_ANGSTROM = None
FULLSPACE_RMSD_SCALE_MULTIPLIER = 10.0
FULLSPACE_MIN_RESIDUAL_SCALE_ANGSTROM = 1.0e-3
FULLSPACE_FAILURE_PENALTY = 1.0e6


def movement_band_fractions():
    """Return the ordered movement-band fractions used by ARIADNE."""
    return {
        "hard_min": MOVEMENT_BAND_HARD_MIN_FRACTION,
        "target_low": MOVEMENT_BAND_TARGET_LOW_FRACTION,
        "target_peak": MOVEMENT_BAND_TARGET_PEAK_FRACTION,
        "target_high": MOVEMENT_BAND_TARGET_HIGH_FRACTION,
        "hard_max": MOVEMENT_BAND_HARD_MAX_FRACTION,
    }


__all__ = [
    "FULLSPACE_FAILURE_PENALTY",
    "FULLSPACE_FIXED_RESIDUAL_SCALE_ANGSTROM",
    "FULLSPACE_MIN_RESIDUAL_SCALE_ANGSTROM",
    "FULLSPACE_RESIDUAL_SCALE",
    "FULLSPACE_RMSD_SCALE_MULTIPLIER",
    "GEOMETRY_NOVELTY_SCORE_TRANSFORM",
    "MOVEMENT_BAND_ENABLED",
    "MOVEMENT_BAND_HARD_MAX_FRACTION",
    "MOVEMENT_BAND_HARD_MIN_FRACTION",
    "MOVEMENT_BAND_LOCAL_STATISTIC",
    "MOVEMENT_BAND_METRIC",
    "MOVEMENT_BAND_TARGET_HIGH_FRACTION",
    "MOVEMENT_BAND_TARGET_LOW_FRACTION",
    "MOVEMENT_BAND_TARGET_PEAK_FRACTION",
    "MOVEMENT_UTILITY_BAND_FRACTION",
    "MOVEMENT_UTILITY_DIRECTION",
    "MOVEMENT_UTILITY_ENABLED",
    "MOVEMENT_UTILITY_HIGH_SOFTNESS_FRACTION",
    "MOVEMENT_UTILITY_LAMBDA_MOVE",
    "MOVEMENT_UTILITY_LOW_SOFTNESS_FRACTION",
    "MOVEMENT_UTILITY_PROGRESS_FRACTION",
    "PHASE_B_MIN_SEPARATION_SCALE",
    "movement_band_fractions",
]
